### ISSUE TITLE
Still learning Java...need help with removal of package javax.xml.bind

### ISSUE THREAD

**Issue by KaLaUnlimited** [arianne/marauroa#17]
Hello, I am  student using your repo for an assignment. I am still kind of new to java and I am wondering about package javax.xml.bind. When running the project, it does not exits. What would be another option? The import is found in marauroa\common\net\message\TransferContent.java.

**Comment by kiheru** [comment]
Hello. That is a package that was removed (without prior warning) in Java 9. The simplest fix is using an older Java version (that's what we do, at least for now). Java 8 has a Base64 class that has the functionality we use, but we haven't started using it yet.

(Here's some more information and alternatives: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j )

**Comment by nhnb** [comment]
This took way longer than I should have, but I finally fixed the issue.
