### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by maxgmer** [arianne/marauroa#18]
I am looking for a framework for a game server, and your server seems really great. The one question I have is does it spawn a separate thread for every client or it uses java nio for async client handling with flexible thread count?

**Comment by nhnb** [comment]
Hello maxgmer!

Marauroa does make use of NIO asynchronous communication without blocking threads. So there is one thread handling communication with Java clients  and a tiny pool of threads handling communication with webclients.

The game loop runs on another thread and finally there is a thread for asynchronous communication with the database server. So even if the database server is extremely busy (e. g. during backup) or needs to be restarted, the game loop will not be affected. Only logins will be delayed as that is the only operation that needs to wait for a result from the database before a player can continue.
